### ISSUE TITLE
Add image to clipboard for copy and paste

### ISSUE THREAD

**Issue by amanthapar** [hugocxl/react-to-image#1]
hi if I wanted to press the button to have the image copied to a clipboard, how would that work? Thank you! (so i can paste image into another application)

**Comment by hcorta** [comment]
Hi @amanthapar!
you may pass a custom callback to get get the Blob written to the clipboard instead of downloading it.

`
const {
  getBlob,
} = useToImage(options, props => {
     // connect with the clipboard here
})
`

Just attach the getBlob function to your listener to be called as you need it, and it should work.
Hope that helps!

**Comment by amanthapar** [comment]
Thanks... I'm trying this. (I call getBlob() in the clickhandler function), but doesn't seem to work... any idea why? Thanks in advance.. 
```
const { ref, getJpeg, getBlob } = useToImage({ backgroundColor: 'white' }, props => {
    return navigator.clipboard.writeText(props.data)
})
```

**Comment by hcorta** [comment]
@amanthapar can you prepare a codesandbox or similar with your example so I can give it a look?

**Comment by Utkarshbhimte** [comment]
I have facing the same problem. Will try to setup a codesandbox if this is not resolved yet

**Comment by hugocxl** [comment]
@amanthapar @Utkarshbhimte I just published a new lib (`@hugocxl/react-to-image`) with several improvements and adjustments where this issue is fixed. I put your case in the documentation. Sorry for the inconvenience 🙏, it's mainly due to NPM restrictions regardless usernames and packages published.
