### ISSUE TITLE
When Using iOS Chrome, the image element is not rendering.

### ISSUE THREAD

**Issue by dotslashf** [hugocxl/react-to-image#80]
Exporting from chrome on desktop (mac) works fine, resulting this:
![1700126149021](https://github.com/hugocxl/react-to-image/assets/38921923/a6d3dd75-1a2b-4062-bffd-d2439089b6b9)

But when im using it from mobile, it result this:
![photo_2023-11-16_17-17-56](https://github.com/hugocxl/react-to-image/assets/38921923/02676fbe-dc71-42f5-a7aa-2cd48ffb5245)

**Comment by hugocxl** [comment]
hi @dotslashf, could you provide a reproducible example so I can dive deeper into the issue?
Thanks!

**Comment by mik593** [comment]
Assuming it's related to issue in html-to-image
#https://github.com/bubkoo/html-to-image/issues/420
