### ISSUE TITLE
Console warning

### ISSUE THREAD

**Issue by uibprodo** [hugocxl/react-to-image#89]
Im using the module in a next js (13.4.7 - app router) application. Im getting this warning on the dev server console 

./node_modules/@hugocxl/react-to-image/dist/chunk-RQMCT6SI.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

Import trace for requested module:
./node_modules/@hugocxl/react-to-image/dist/chunk-RQMCT6SI.js
./node_modules/@hugocxl/react-to-image/dist/index.js

Im using the useToCanvas canvas hook

**Comment by hugocxl** [comment]
@uibprodo does the warning prevent the hook from being used correctly?

**Comment by uibprodo** [comment]
@hugocxl it works fine (Its a really good module) checking out whether its a known issue and if theres a way to mitigate it

**Comment by hugocxl** [comment]
Mmm Next is shipping so many breaking changes lately is difficult to keep up to date with the framework. 
I'll try to give it a look when I find some time, but in the meantime I'll mark it as enhancement since it does not prevent the lib from being used.

**Comment by kitze** [comment]
@hugocxl this library looks amazing. I'm getting this error when I try to use it though :(
![CleanShot 2024-01-19 at 13 08 55@2x](https://github.com/hugocxl/react-to-image/assets/1160594/6cc8562b-99a6-4d3f-a723-3ab65c99ff10)

**Comment by hugocxl** [comment]
Hi @kitze! Could you provide more info and possibly a reproducible example? That would help to dig into the issue
